play_motion:
  motions:
    pregrasp:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.34, 1.61, -1.17, -3.17, 2.29, -1.58, -1.25, 0.00]
        time_from_start: 6.0

    head_look_around:
      joints: [head_1_joint, head_2_joint]
      points:
      - positions: [0, 0]
        time_from_start: 1.0
      - positions: [0, 0]
        time_from_start: 2.0
      - positions: [0, -0.7]
        time_from_start: 5.0
      - positions: [0, -0.7]
        time_from_start: 6.0
      - positions: [-0.7, -0.7]
        time_from_start: 9.0
      - positions: [-0.7, -0.7]
        time_from_start: 10.0
      - positions: [-0.7, -0.5]
        time_from_start: 13.0
      - positions: [-0.7, -0.5]
        time_from_start: 14.0
      - positions: [0, -0.5]
        time_from_start: 17.0
      - positions: [0, -0.5]
        time_from_start: 18.0
      - positions: [0.7, -0.5]
        time_from_start: 21.0
      - positions: [0.7, -0.5]
        time_from_start: 22.0
      - positions: [0.7, -0.7]
        time_from_start: 25.0
      - positions: [0.7, -0.7]
        time_from_start: 26.0
      - positions: [0, -0.7]
        time_from_start: 29.0
      - positions: [0, -0.7]
        time_from_start: 30.0
      - positions: [0, -0.5]
        time_from_start: 34.0
      
   
    
      

        

